image: fedora/latest
packages:
  - tar
tasks:
  - chezmoi-init: |
      sh -c "$(curl -fsLS get.chezmoi.io)" -- init --promptDefaults --apply https://git.sr.ht/~code-runner/dotfiles
  - emacs: |
      emacs --debug-init --batch -u $USER
  - zsh: |
      $(chezmoi source-path)/ci/test_zsh.sh
