image: nixos/unstable
packages:
  - nixos.emacs
  - nixos.chezmoi
  - nixos.zsh
secrets:
  - 572eda84-1c09-4239-a0f3-0c8d1a8df472
sources:
  - git@git.sr.ht:~code-runner/dotfiles
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - chezmoi-init: |
      chezmoi init --promptDefaults --apply https://git.sr.ht/~code-runner/dotfiles
  - zsh: |
      $(chezmoi source-path)/ci/test_zsh.sh
  - emacs: |
      emacs --debug-init --batch -u $USER
  - mirror: |
      cd dotfiles
      git push --force --mirror git@codeberg.org:code-runner/dotfiles.git
      git push --force --mirror git@github.com:ethan-coe-renner/dotfiles.git
