image: fedora/latest
packages:
  - tar
secrets:
  - 3e0c09c0-77d5-497e-acfc-16c249b99d0e
sources:
  - git@git.sr.ht:~code-runner/dotfiles
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - chezmoi-init: |
      sh -c "$(curl -fsLS get.chezmoi.io)" -- init --promptDefaults --apply https://git.sr.ht/~code-runner/dotfiles
  - emacs: |
      emacs --debug-init --batch -u $USER
  - zsh: |
      $(chezmoi source-path)/ci/test_zsh.sh
  - mirror: |
      cd dotfiles
      git push --force --mirror git@codeberg.org:code-runner/dotfiles.git
      git push --force --mirror git@gitlab.com:code-runner/dotfiles.git
