[".config/zsh/antigen.zsh"]
	type = "file"
	url = "https://git.io/antigen"
	refreshPeriod = "672h"

{{- if eq .tag "personal" }}
["git/nixos-config"]
    type = "git-repo"
    url = "git@git.sr.ht:~code-runner/nixos-config"

["org"]
    type = "git-repo"
    url = "git@git.sr.ht:~code-runner/org"

["git/finance-extras"]
    type = "git-repo"
    url = "git@git.sr.ht:~code-runner/finance-extras"
{{ end }}

["git/ghostty-themes"]
    type = "git-repo"
    url = "https://codeberg.org/anhsirk0/ghostty-themes.git"

